### PR TITLE
Syntax issues for README

### PR DESCRIPTION
**Pull request by roclark**
Fixed an issue with the ssh-keygen command placing the hyphen in the proper place. Also added a note about disabling requiretty.

### CODE REVIEW

**Comment by joehandzik** [comment]
Look like helpful additions, Mr. Clark. I notice that you changed the wrapping behavior of the README...I agree with your changes, but someone may come back and request that you make the line length changes separate from the ssh-keygen change. Make sense?

**Comment by roclark** [comment]
Thanks for the find! Fixed the issues on my side so now I made the changes to the current version of README.md in the upstream master. Now it just includes the fixes for the ssh-keygen and the note about requirestty.

**Comment by roclark** [comment]
Hey @markhpc, does this look ok?

**Comment by markhpc** [comment]
Yep, lgtm!

**Pull request closed without merging**
