### PR TITLE
fio_objectstore_tools: utilities for tracing fio_ceph_objectstore

### PR DESCRIPTION
**Pull request by athanatos**
This adds a few python scripts for initializing, running, and
analyzing benchmark runs using the fio_ceph_objectstore backend.

The tooling is focused on understanding the
latency/throttle/throughput relationship for a particular
device.

Signed-off-by: Samuel Just <sjust@redhat.com>

### CODE REVIEW

**Comment by athanatos** [comment]
The next step would be to incorporate support for running the lttng sessions and collecting trace results into cbt proper.

**Comment by athanatos** [comment]
@markhpc Does this look appropriate?

**Comment by markhpc** [comment]
@athanatos looks good, though maybe move the fio_objecstore_tools directory under the top level tools directory?

**Comment by athanatos** [comment]
@markhpc will do

**Pull request merged**
